### ISSUE TITLE
Change mp3 settings

### ISSUE THREAD

**Issue by AXiSource** [kelciour/create-subs2srs-cards-with-mpv-video-player#10]
Can you help me switch to mono, VBR, change the bitrate and frequency of the mp3 generated ?

**Comment by kelciour** [comment]
Anki > Tools > Add-ons > Create subs2srs ... > View Files, edit `mpv2anki.py` by modifying `subprocess_audio` (Line 605) and restart Anki.

For example (not tested), by adding this line after `argv += ["-vn"]` (Line 615) for encoding with FFmpeg ("Use MPV" in the add-on's window is not checked)

```python
            argv += ["-b:a", "64k", "-ac", "1"]
```

or after line 623 for encoding with mpv ("Use MPV" is checked)

```python
            argv += ['--audio-channels=mono']
            argv += ['--oacopts=b=64k']
```

**Comment by AXiSource** [comment]
Can you add the frequency aka sample rate command please ?

Anyway Many Thanks to you already, it worked !

**Comment by kelciour** [comment]
Maybe something like this (not tested).

For ffmpeg, 

```
            argv += ["-ar", "16000"]
```

For mpv,

```
            argv += ['--audio-samplerate=16000']
```
