### ISSUE TITLE
Can't seem to get any images to work properly on ubuntu

### ISSUE THREAD

**Issue by rmikedown** [kelciour/create-subs2srs-cards-with-mpv-video-player#4]
First of all, just want to say this is quite amazing what you've done with this. I think I prefer this to even mpvacious after messing around with it. The flashcard outputs are easily customizable. 

Something that I've come across after using both this and mpvacious is that I think my mpv might have some issues with generating the picture files. I ran this add-on in windows without issue. I find this issue to be odd because the mpv version I downloaded (which is found here): https://launchpad.net/~mc3man/+archive/ubuntu/mpv-tests
is the main one recommended on the mpv installation page: https://mpv.io/installation/

Mpvacious allows you to adjust some scripts and when I allowed ffmpeg to create the images instead of mpv it allows screenshots to work on most videos. I'm wondering if there's any insight into what's going on? Is there any setting I can change to fix my image issue, or do I need to maybe find a different version of mpv?

**Comment by kelciour** [comment]
Thank you for the kind words!

I can't seem to reproduce the issue on Ubuntu 21.10. 

```
mpv 0.33.0 Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Tue Dec  8 19:04:35 UTC 2020
FFmpeg library versions:
   libavutil       56.60.100
   libavcodec      58.112.103
   libavformat     58.64.100
   libswscale      5.8.100
   libavfilter     7.90.100
   libswresample   3.8.100
FFmpeg version: git-2020-11-22-9208b72
```

Aside from unchecking "Use MPV?" and use ffmpeg for encoding (if you only need it with local video files), maybe start Anki from the terminal this way `ADDON_DEBUG=1 anki` and use the add-on to create a card. The terminal will contain the exact command that was used for encoding and there probably will be some error message. To make the command work in the terminal, the path to the video file might need to be wrapped with double quotes, e.g. if it contains curly brackets.

For example,

> DEBUG: /usr/bin/mpv -v /home/nickolay/Downloads/video.mkv --include=/home/nickolay/.local/share/Anki2/addons21/1213145732/user_files/mpv.conf --start=00:14:20.720 --audio=no --sub=no --sub-visibility=yes --sub-delay=0.000000 --frames=1 --vf-add=lavfi-scale=-2:320 --vf-add=format=fmt=yuvj422p --ovc=mjpeg "--o=/home/nickolay/.local/share/Anki2/User 1/collection.media/video_00.14.20.720.jpg"

**Comment by rmikedown** [comment]
It seems if I uncheck use mpv it does work now. I didn't even think about the possibility because in my head I'm like "of course I want to use mpv!"

Thanks for taking your time to make this project and answer these types of questions :)

FYI:
I've got the same exact FFmpeg version as you.

FFmpeg library versions:
libavutil 56.60.100
libavcodec 58.112.103
libavformat 58.64.100
libswscale 5.8.100
libavfilter 7.90.100
libswwresample 3.8.100
